version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: 222_cassandra
    ports:
      - 9042:9042
    # volumes:
    #   - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra

  db:
    image: mysql:latest
    container_name: 222_mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
#     volumes:
#       - my_datavolume:/var/lib/mysql
#       # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# volumes:
#   my_datavolume:
    
